apiVersion: v1
kind: ReplicationController 
metadata: 
   name: vertex-rc
spec: 
   replicas: 5
   selector: 
     app: vertexapp
     version: 2.6.2
   template: 
     metadata: 
       labels:
          app: vertexapp
          version: 2.6.2
     spec: 
         containers:
         - name: mytomcat-container
           image: aishwarya5502/myjavaimage16nov22
           ports:
           - containerPort: 8080      
  
